"""
VLA (Vision-Language-Action) Module Models
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class VoiceCommand(BaseModel):
    """
    Represents a spoken instruction from the user, containing raw audio and transcribed text
    """
    id: str
    audio_data: Optional[str] = None  # Base64 encoded audio data
    transcribed_text: str
    timestamp: datetime = Field(default_factory=datetime.now)
    confidence: float = 1.0  # Speech recognition confidence (0.0-1.0)


class LanguagePlan(BaseModel):
    """
    Contains the interpreted meaning of the command and high-level action sequence generated by the LLM
    """
    id: str
    command_id: str  # Reference to VoiceCommand.id
    interpreted_meaning: str
    action_sequence: List[Dict[str, Any]]  # List of action dictionaries
    generated_by_llm: str  # Which LLM was used
    timestamp: datetime = Field(default_factory=datetime.now)


class RobotAction(BaseModel):
    """
    Low-level control commands that drive the simulated humanoid's movements and behaviors
    """
    id: str
    action_type: str  # e.g., "move_forward", "raise_arm", "turn_left"
    parameters: Dict[str, Any]  # Action-specific parameters
    execution_priority: int = 0
    estimated_duration_ms: Optional[int] = None


class SimulationEnvironment(BaseModel):
    """
    Virtual space where the humanoid robot operates, containing objects and spatial information
    """
    id: str
    name: str
    description: str
    objects: List[Dict[str, Any]]  # List of objects in the environment
    spatial_info: Dict[str, Any]  # Spatial relationships and coordinates
    timestamp: datetime = Field(default_factory=datetime.now)


class VLAPipelineStatus(str, Enum):
    """
    Status of the VLA pipeline execution
    """
    PENDING = "pending"
    PROCESSING_SPEECH = "processing_speech"
    GENERATING_PLAN = "generating_plan"
    EXECUTING_ACTIONS = "executing_actions"
    COMPLETED = "completed"
    FAILED = "failed"


class VLAPipeline(BaseModel):
    """
    Represents a complete VLA pipeline execution from voice command to robot action
    """
    id: str
    voice_command: VoiceCommand
    language_plan: Optional[LanguagePlan] = None
    robot_actions: List[RobotAction] = Field(default_factory=list)
    simulation_environment: Optional[SimulationEnvironment] = None
    status: VLAPipelineStatus = VLAPipelineStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.now)
    completed_at: Optional[datetime] = None
    error_message: Optional[str] = None